name: Deploy

on:
  workflow_dispatch:

jobs:
  deploy:
    uses: Akki-8989/Infrastructure/.github/workflows/deploy-frontend.yml@main
    with:
      repo_name: ui-node-app
      infra_repo: Infrastructure
      backend_urls: https://be-node-products-webapp.azurewebsites.net,https://be-node-orders-webapp.azurewebsites.net
    secrets: inherit
