name: Deploy

on:
  workflow_dispatch:

jobs:
  deploy:
    uses: Akki-8989/Infrastructure/.github/workflows/deploy-backend.yml@main
    with:
      repo_name: ui-node-app
      infra_repo: Infrastructure
      database_type: sqlserver
      database_name: ecom_db
      tier: free
    secrets: inherit
